CONFIG_FILE: str = "config.json"
DOCKER_NAMESPACE: str = "pdfix"
DOCKER_REPOSITORY: str = "pdf-accessibility-paddle"
DOCKER_IMAGE: str = f"{DOCKER_NAMESPACE}/{DOCKER_REPOSITORY}"
IMAGE_FILE_EXT_REGEX: str = r"\.(jpg|jpeg|png|bmp)$"
MATH_ML_VERSION: str = "mathml-3"
PERCENT_AI: float = 0.8
PERCENT_RENDER: float = 0.1
PERCENT_TEMPLATE: float = 0.1
PROGRESS_FIRST_STEP: int = 10  # Initialize (open document, read page count, etc.)
PROGRESS_FOURTH_STEP: int = 80  # Autotagging and saving document/data
PROGRESS_SECOND_STEP: int = 900  # Run AI heavy workload (+ rendering + template conversion)
PROGRESS_THIRD_STEP: int = 10  # Save template or prepare it for autotagging
SUPPORTED_IMAGE_EXT: str = ".jpg .jpeg .png .bmp"
